services:
  tubecast:
    image: tubecast:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tubecast
    env_file: .env
    volumes:
      - type: bind
        source: ./docs
        target: /app/docs
      - type: bind
        source: ./tubecast/station
        target: /app/tubecast/station
      - type: bind
        source: ./tubecast/cover
        target: /app/tubecast/cover
      - type: bind
        source: ${HOME_DIR}/.config/internetarchive/ia.ini
        target: /root/.config/internetarchive/ia.ini
        read_only: true