services:
  tubecast:
    image: ihtemad/tubecast
    container_name: tubecast
    env_file: .env
    volumes:
      - type: bind
        source: ./docs
        target: /app/docs
      - type: bind
        source: ./tubecast/cover
        target: /app/tubecast/cover
      - type: bind
        source: ${HOME_DIR}/.config/internetarchive/ia.ini
        target: /root/.config/internetarchive/ia.ini
        read_only: true
      - type: volume
        source: station
        target: /app/tubecast/station
volumes:
  station: {}