name: Podcast Sync (Optimized)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      sync_type:
        description: 'Type of sync to perform'
        required: false
        default: 'full'
        type: choice
        options:
          - full
          - quick

jobs:
  sync-podcast:
    runs-on: macos-latest
    
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # 2. Set up Go using marketplace action (recommended)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true
          
      # 3. Install Homebrew tools with caching
      - name: Install Homebrew tools
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: yt-dlp ffmpeg fprobe
          
      # 4. Build Go application
      - name: Build Go application
        run: go build -o tubecast ./cmd/main.go
        
      # 5. Run the application
      - name: Run podcast sync
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./tubecast sync
        
      # 6. Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update podcast feed [skip ci]"
            git push
          fi
