name: Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-podcast:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yt-dlp
        run: |
          mkdir -p "$HOME/bin"
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos -o "$HOME/bin/yt-dlp"
          chmod +x "$HOME/bin/yt-dlp"
          echo "$HOME/bin" >> "$GITHUB_PATH"

      - name: Prepare cookies file
        run: |
          echo "${{ secrets.COOKIE_TXT }}" > cookies.txt

      - name: Build Go application
        run: |
          go build -o tubecast.o .

      - name: Configure Internet Archive CLI
        run: |
          chmod +x ./ia
          mkdir -p ~/.config/internetarchive
          cat > ~/.config/internetarchive/ia.ini <<EOF
          [s3]
          access = ${{ secrets.IA_S3_ACCESS_KEY }}
          secret = ${{ secrets.IA_S3_SECRET_KEY }}
          EOF

      - name: Run sync
        env:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./tubecast.o -sync

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update podcast feed [skip ci]"
            git push
          fi
