name: Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-podcast:
    runs-on: macos-15

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Go (with caching)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true

      # 3. Download yt-dlp and FFmpeg static builds (no Homebrew)
      - name: Install yt-dlp and FFmpeg
        run: |
          mkdir -p $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH

          # yt-dlp (latest release)
          YTDLP_URL=https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos
          curl -L $YTDLP_URL -o $HOME/bin/yt-dlp
          chmod +x $HOME/bin/yt-dlp

          # FFmpeg static build (macOS x86_64 or arm64—pick matching runner)
          FFMPEG_URL=https://evermeet.cx/ffmpeg/ffmpeg-6.0.zip
          curl -L $FFMPEG_URL -o /tmp/ffmpeg.zip
          unzip -j /tmp/ffmpeg.zip -d $HOME/bin ffmpeg ffprobe
          chmod +x $HOME/bin/ffmpeg $HOME/bin/ffprobe

      # 4. Build Go application
      - name: Build Go application
        run: |
          go build -o tubecast.o .
          mkdir -p $HOME/bin
          install -m0755 tubecast.o $HOME/bin/tubecast

      # 5. Configure Internet Archive CLI
      - name: Configure Internet Archive CLI
        run: |
          chmod +x ./ia
          mkdir -p ~/.config/internetarchive
          cat > ~/.config/internetarchive/ia.ini <<EOF
          [s3]
          access = ${{ secrets.IA_S3_ACCESS_KEY }}
          secret = ${{ secrets.IA_S3_SECRET_KEY }}
          EOF

      # 6. Run the application
      - name: Run sync
        env:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tubecast -sync

      # 7. Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update podcast feed [skip ci]"
            git push
